### ISSUE TITLE
Add sensors from Vega 10 and later series

### ISSUE THREAD

**Issue by PatrickSzela** [PatrickSzela/ksysguard-amdgpu#3]
According to the [Linux Kernel Documentation](https://dri.freedesktop.org/docs/drm/gpu/amdgpu.html#gpu-power-thermal-controls-and-monitoring) with Vega 10 and 20 series the driver exposes some additional interfaces.

I would be grateful if someone with card from these series would upload (from `/sys/bus/pci/drivers/amdgpu/<PCI_SLOT>/` directory) content of these files:
1. Vega 10 and later:
    1. `pp_dpm_socclk` ✅
    2. `pp_dpm_dcefclk` ✅
2. Vega 20 and later: 
    1. `pp_dpm_fclk` ✅

**Comment by ghost** [comment]
From my Vega 64 (Vega10):

- pp_dpm_socclk:
```
0: 600Mhz *
1: 720Mhz
2: 800Mhz
3: 847Mhz
4: 900Mhz
5: 960Mhz
6: 1028Mhz
7: 1107Mhz
```
- pp_dpm_dcefclk:
```
0: 600Mhz *
1: 720Mhz
2: 800Mhz
3: 847Mhz
4: 900Mhz
```

**Comment by PatrickSzela** [comment]
Thank you for sharing the content of these files!
So it looks like, in comparison to other `pp_dpm_*` files, the current state of `socclk` and `dcefclk` isn't marked at all (with a `*`). Interesting... I guess it's time to dig in into the driver's source code.

**Comment by ghost** [comment]
My mistake. I accidentally deleted the * since I just thought you wanted the different state. Since the card was idling when I was posting, a * was used on state 0 on both. I've updated the original comment.

**Comment by PatrickSzela** [comment]
Thank you for the update! In that case, these 2 sensors will be added soon(-ish)

**Comment by xbjfk** [comment]
Hello, I have a RX 5700 XT (Navi 10). The contents of `pp_dpm_fclk` are:

```
0: 506Mhz 
1: 950Mhz *
2: 1266Mhz 
```
EDIT: Formatting

**Comment by PatrickSzela** [comment]
Thank you all for sending me these files! I've managed to get all three sensors to work - while using my "dummy files" - and I hope it will also work with the actual ones.
