### ISSUE TITLE
Gracefully handle missing monitors

### ISSUE THREAD

**Issue by soofstad** [PatrickSzela/ksysguard-amdgpu#5]
Hi,
I just tested this with my AMD RX 5700 XT with kernel v.5.3.0-26-generic and mesa v.19.2.1.
Got some errors referring to missing monitor files, namely "pp_od_clk_voltage".
Found this; https://patchwork.freedesktop.org/series/69152/
Which states that it's not implemented in the drivers for Navi 10 cards yet. Not sure when the patch will be merged.

I can try and make a PR where errors like this, which are bound to show up in future cards/drivers as well, are handled gracefully, so the script at least works, just not  list the sensor in KSysGuard.

**Comment by PatrickSzela** [comment]
Well actually, the script already does that - if the required file is missing, can't be read or parsed, the monitor should not show up.

And looking at the commits in the Linux kernel source code, the patch mentioned by you has been already commited to the master branch on [Nov 8th](https://github.com/torvalds/linux/commit/21677d0880957a81910d83f042e788b684472d1e).

Could you include the full output of the script with `--logging` argument?

**Comment by soofstad** [comment]
Huh, very strange.
Read this comment, https://github.com/PatrickSzela/ksysguard-amdgpu/issues/4#issuecomment-573436377

And I got almost the exact same behavior.
After a reboot and restarting KSysguard, the "remote host" pops up with all  the expected sensors.
